import type { OrderMenuItem } from "../types";

/**
 * Order-flow mains. Built on the 16 real meals (with their genuine
 * photography) and extended with Traditional South African favourites and
 * Winter Warmers. Each item carries `goalTags` so the menu filters to the
 * guest's onboarding goal, and a `paletteId` so its card can glow in the
 * matching brand colour.
 */
export const MAINS: readonly OrderMenuItem[] = Object.freeze([
  // --- In demand this week (winter warmers + signatures) ---
  Object.freeze({
    id: "winter-oxtail-stew",
    name: "Oxtail Stew",
    description: "Slow-braised oxtail in a rich, hearty gravy. The winter warmer everyone's ordering.",
    priceDisplay: "R159",
    price: 159,
    course: "main",
    imageSrc: "/images/meals/beef-premium/oxtail-stew.webp",
    imageAlt: "Oxtail stew",
    paletteId: "espresso",
    goalTags: Object.freeze(["high-protein", "iron-rich", "nourishing", "comfort"]),
    isSignature: true,
  }),
  Object.freeze({
    id: "sa-roast-chicken-seven-colours",
    name: "Roast Chicken Seven Colours",
    description: "The traditional Sunday spread — roast chicken with seven vibrant sides.",
    priceDisplay: "R129",
    price: 129,
    course: "main",
    imageSrc: "/images/meals/sunday-lunch/roast-chicken-seven-colours.webp",
    imageAlt: "Roast chicken seven colours",
    paletteId: "blood-red",
    goalTags: Object.freeze(["high-protein", "comfort", "nourishing"]),
    isSignature: true,
  }),
  Object.freeze({
    id: "winter-lamb-chops",
    name: "Char-Grilled Lamb Chops",
    description: "Herb-seasoned lamb chops, char-grilled. A cold-weather favourite.",
    priceDisplay: "R169",
    price: 169,
    course: "main",
    imageSrc: "/images/meals/beef-premium/lamb-chops.webp",
    imageAlt: "Lamb chops",
    paletteId: "bean",
    goalTags: Object.freeze(["high-protein", "low-carb", "iron-rich"]),
    isSignature: true,
  }),

  // --- Healthy / light ---
  Object.freeze({
    id: "healthy-chicken-gyro-bowl",
    name: "Chicken Gyro Bowl",
    description: "Grilled chicken, fresh greens and a light tzatziki drizzle.",
    priceDisplay: "R89",
    price: 89,
    course: "main",
    imageSrc: "/images/meals/healthy/chicken-gyro-bowl.webp",
    imageAlt: "Chicken gyro bowl with fresh vegetables",
    paletteId: "olive",
    goalTags: Object.freeze(["light", "high-protein", "mediterranean", "low-carb"]),
  }),
  Object.freeze({
    id: "healthy-burger-bowl",
    name: "Burger Bowl",
    description: "Deconstructed burger flavours over crisp greens.",
    priceDisplay: "R85",
    price: 85,
    course: "main",
    imageSrc: "/images/meals/healthy/burger-bowl.webp",
    imageAlt: "Burger bowl with lean mince and salad",
    paletteId: "olive",
    goalTags: Object.freeze(["high-protein", "low-carb", "iron-rich"]),
  }),
  Object.freeze({
    id: "healthy-chicken-salad-bowl",
    name: "Chicken Salad Bowl",
    description: "Lean chicken breast with a colourful vegetable medley.",
    priceDisplay: "R79",
    price: 79,
    course: "main",
    imageSrc: "/images/meals/healthy/chicken-salad-bowl.webp",
    imageAlt: "Chicken salad bowl",
    paletteId: "lemon-cream",
    goalTags: Object.freeze(["light", "high-protein", "low-carb", "plant-forward", "mediterranean"]),
  }),

  // --- Chicken ---
  Object.freeze({
    id: "chicken-peri-peri",
    name: "Peri-Peri Chicken",
    description: "Flame-grilled chicken basted in fiery peri-peri sauce.",
    priceDisplay: "R95",
    price: 95,
    course: "main",
    imageSrc: "/images/meals/chicken/peri-peri-chicken.webp",
    imageAlt: "Peri-peri chicken",
    paletteId: "persimmon",
    goalTags: Object.freeze(["high-protein", "low-carb"]),
    isSignature: true,
  }),
  Object.freeze({
    id: "chicken-bbq",
    name: "BBQ Chicken",
    description: "Smoky BBQ glazed chicken, grilled to perfection.",
    priceDisplay: "R92",
    price: 92,
    course: "main",
    imageSrc: "/images/meals/chicken/bbq-chicken.webp",
    imageAlt: "BBQ chicken",
    paletteId: "persimmon",
    goalTags: Object.freeze(["high-protein", "comfort"]),
  }),
  Object.freeze({
    id: "chicken-roasted",
    name: "Roasted Chicken",
    description: "Slow-roasted chicken with golden crispy skin.",
    priceDisplay: "R99",
    price: 99,
    course: "main",
    imageSrc: "/images/meals/chicken/roasted-chicken.webp",
    imageAlt: "Roasted chicken",
    paletteId: "vanilla",
    goalTags: Object.freeze(["high-protein", "low-carb", "nourishing"]),
  }),

  // --- Beef & premium ---
  Object.freeze({
    id: "beef-steak-chips",
    name: "Steak & Chips",
    description: "Tender grilled steak served with crispy golden chips.",
    priceDisplay: "R149",
    price: 149,
    course: "main",
    imageSrc: "/images/meals/beef-premium/steak-and-chips.webp",
    imageAlt: "Steak and chips",
    paletteId: "espresso",
    goalTags: Object.freeze(["high-protein", "iron-rich", "comfort"]),
  }),
  Object.freeze({
    id: "sa-oxtail-seven-colours",
    name: "Oxtail Seven Colours",
    description: "Rich oxtail served the traditional Sunday way.",
    priceDisplay: "R159",
    price: 159,
    course: "main",
    imageSrc: "/images/meals/sunday-lunch/oxtail-seven-colours.webp",
    imageAlt: "Oxtail seven colours",
    paletteId: "blood-red",
    goalTags: Object.freeze(["high-protein", "iron-rich", "nourishing", "comfort"]),
    isSignature: true,
  }),

  // --- Breakfast / gentle ---
  Object.freeze({
    id: "breakfast-overnight-oats",
    name: "Overnight Oats",
    description: "Creamy oats soaked overnight with fruit and honey.",
    priceDisplay: "R55",
    price: 55,
    course: "main",
    imageSrc: "/images/meals/breakfast/overnight-oats.webp",
    imageAlt: "Overnight oats",
    paletteId: "vanilla",
    goalTags: Object.freeze(["light", "plant-forward", "nourishing"]),
  }),

  // --- Pasta & kid friendly ---
  Object.freeze({
    id: "pasta-beef-lasagne",
    name: "Beef Lasagne",
    description: "Layers of pasta, beef ragu and melted cheese.",
    priceDisplay: "R89",
    price: 89,
    course: "main",
    imageSrc: "/images/meals/pasta-bakes/beef-lasagne.webp",
    imageAlt: "Beef lasagne",
    paletteId: "strawberry",
    goalTags: Object.freeze(["comfort", "iron-rich", "nourishing"]),
  }),
  Object.freeze({
    id: "pasta-meatball",
    name: "Meatball Pasta",
    description: "Juicy meatballs tossed in rich tomato pasta.",
    priceDisplay: "R85",
    price: 85,
    course: "main",
    imageSrc: "/images/meals/pasta-bakes/meatball-pasta.webp",
    imageAlt: "Meatball pasta",
    paletteId: "strawberry",
    goalTags: Object.freeze(["high-protein", "comfort"]),
  }),
  Object.freeze({
    id: "pasta-cheesy-mince",
    name: "Cheesy Mince Pasta",
    description: "Kid-friendly cheesy mince pasta bake.",
    priceDisplay: "R79",
    price: 79,
    course: "main",
    imageSrc: "/images/meals/pasta-bakes/cheesy-mince-pasta.webp",
    imageAlt: "Cheesy mince pasta",
    paletteId: "strawberry",
    goalTags: Object.freeze(["comfort", "nourishing"]),
  }),
  Object.freeze({
    id: "sa-chicken-seven-colours",
    name: "Chicken Seven Colours",
    description: "Classic chicken Sunday lunch with seven colourful sides.",
    priceDisplay: "R119",
    price: 119,
    course: "main",
    imageSrc: "/images/meals/sunday-lunch/chicken-seven-colours.webp",
    imageAlt: "Chicken seven colours",
    paletteId: "blood-red",
    goalTags: Object.freeze(["high-protein", "comfort", "nourishing"]),
    isSignature: true,
  }),
]);

export const SIDES: readonly OrderMenuItem[] = Object.freeze([
  Object.freeze({
    id: "side-samp-beans",
    name: "Samp & Beans",
    description: "Slow-cooked umngqusho — a true SA staple.",
    priceDisplay: "R35",
    price: 35,
    course: "side",
    imageSrc: "/images/loop/meal-6.webp",
    imageAlt: "Samp and beans",
    paletteId: "warm-linen",
    goalTags: Object.freeze(["comfort", "plant-forward"]),
    isSignature: true,
  }),
  Object.freeze({
    id: "side-chakalaka",
    name: "Chakalaka",
    description: "Spicy vegetable relish with a kick.",
    priceDisplay: "R30",
    price: 30,
    course: "side",
    imageSrc: "/images/loop/meal-2.webp",
    imageAlt: "Chakalaka",
    paletteId: "persimmon",
    goalTags: Object.freeze(["plant-forward", "light"]),
    isSignature: true,
  }),
  Object.freeze({
    id: "side-roast-veg",
    name: "Honey Roast Veg",
    description: "Seasonal winter vegetables, roasted sweet.",
    priceDisplay: "R38",
    price: 38,
    course: "side",
    imageSrc: "/images/loop/meal-8.webp",
    imageAlt: "Honey roast vegetables",
    paletteId: "vanilla",
    goalTags: Object.freeze(["plant-forward", "light", "mediterranean", "nourishing"]),
  }),
  Object.freeze({
    id: "side-garden-salad",
    name: "Garden Salad",
    description: "Crisp greens with a lemon-olive oil dressing.",
    priceDisplay: "R32",
    price: 32,
    course: "side",
    imageSrc: "/images/loop/meal-1.webp",
    imageAlt: "Garden salad",
    paletteId: "olive",
    goalTags: Object.freeze(["light", "plant-forward", "mediterranean", "low-carb"]),
  }),
  Object.freeze({
    id: "side-pap",
    name: "Creamy Pap",
    description: "Soft maize pap, the comforting classic.",
    priceDisplay: "R25",
    price: 25,
    course: "side",
    imageSrc: "/images/loop/meal-5.webp",
    imageAlt: "Creamy pap",
    paletteId: "lemon-cream",
    goalTags: Object.freeze(["comfort", "nourishing"]),
    isSignature: true,
  }),
]);

export const DESSERTS: readonly OrderMenuItem[] = Object.freeze([
  Object.freeze({
    id: "dessert-malva",
    name: "Malva Pudding",
    description: "Warm, sticky apricot sponge with cream.",
    priceDisplay: "R55",
    price: 55,
    course: "dessert",
    imageSrc: "/images/loop/meal-9.webp",
    imageAlt: "Malva pudding",
    paletteId: "vanilla",
    goalTags: Object.freeze(["comfort"]),
    isSignature: true,
  }),
  Object.freeze({
    id: "dessert-milk-tart",
    name: "Milk Tart",
    description: "Silky cinnamon-dusted custard tart.",
    priceDisplay: "R50",
    price: 50,
    course: "dessert",
    imageSrc: "/images/loop/meal-7.webp",
    imageAlt: "Milk tart",
    paletteId: "lemon-cream",
    goalTags: Object.freeze(["comfort"]),
    isSignature: true,
  }),
  Object.freeze({
    id: "dessert-berry-oats",
    name: "Berry Oat Crumble",
    description: "Baked berries under a golden oat crumble.",
    priceDisplay: "R48",
    price: 48,
    course: "dessert",
    imageSrc: "/images/loop/meal-4.webp",
    imageAlt: "Berry oat crumble",
    paletteId: "strawberry",
    goalTags: Object.freeze(["light", "plant-forward"]),
  }),
]);

export const ALL_MENU_ITEMS: readonly OrderMenuItem[] = Object.freeze([
  ...MAINS,
  ...SIDES,
  ...DESSERTS,
]);

/** The "in demand this week" highlight set — winter warmers + SA favourites. */
export const IN_DEMAND_IDS: readonly string[] = Object.freeze([
  "winter-oxtail-stew",
  "sa-roast-chicken-seven-colours",
  "winter-lamb-chops",
  "sa-oxtail-seven-colours",
]);
